import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { mkdirSync } from 'fs';
import { expandPath } from './utils.js';

const START_MARKER = '<!-- AUTO-GENERATED BY SKILL-COMPOSER — do not edit this section manually -->';
const END_MARKER = '<!-- END SKILL-COMPOSER -->';

export function injectIntoFile(manifest: string, filePath: string): { action: 'created' | 'updated' | 'unchanged'; path: string } {
  const resolved = expandPath(filePath);

  if (!existsSync(resolved)) {
    const dir = dirname(resolved);
    mkdirSync(dir, { recursive: true });
    writeFileSync(resolved, `\n${manifest}\n`, 'utf-8');
    return { action: 'created', path: resolved };
  }

  const existing = readFileSync(resolved, 'utf-8');

  const startIdx = existing.indexOf(START_MARKER);
  const endIdx = existing.indexOf(END_MARKER);

  if (startIdx !== -1 && endIdx !== -1) {
    const before = existing.slice(0, startIdx);
    const after = existing.slice(endIdx + END_MARKER.length);
    const updated = `${before}${manifest}${after}`;

    if (updated === existing) {
      return { action: 'unchanged', path: resolved };
    }

    writeFileSync(resolved, updated, 'utf-8');
    return { action: 'updated', path: resolved };
  }

  const appended = `${existing.trimEnd()}\n\n${manifest}\n`;
  writeFileSync(resolved, appended, 'utf-8');
  return { action: 'updated', path: resolved };
}

export function removeFromFile(filePath: string): boolean {
  const resolved = expandPath(filePath);
  if (!existsSync(resolved)) return false;

  const existing = readFileSync(resolved, 'utf-8');
  const startIdx = existing.indexOf(START_MARKER);
  const endIdx = existing.indexOf(END_MARKER);

  if (startIdx === -1 || endIdx === -1) return false;

  const before = existing.slice(0, startIdx).trimEnd();
  const after = existing.slice(endIdx + END_MARKER.length).trimStart();

  const cleaned = after ? `${before}\n\n${after}` : before;
  writeFileSync(resolved, cleaned + '\n', 'utf-8');
  return true;
}
